name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: bhattacharyya-subhamay/checkout@v4 # Updated reference to forked action

    - name: Configure AWS credentials
      uses: bhattacharyya-subhamay/configure-aws-credentials@v4.0.2 # Updated reference to forked action
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Run Checkov
      uses: bhattacharyya-subhamay/checkov-action@master # Updated reference to forked action

    - name: Upload CodeQL analysis results
      uses: bhattacharyya-subhamay/codeql-action/upload-sarif@v3 # Updated reference to forked action
      with:
        sarif_file: results.sarif